[2022-08-03 00:51:44,306] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:51:41.184193+00:00 [queued]>
[2022-08-03 00:51:44,448] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:51:41.184193+00:00 [queued]>
[2022-08-03 00:51:44,457] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:51:44,511] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 00:51:44,527] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:51:44,685] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-08-03 00:51:41.184193+00:00
[2022-08-03 00:51:44,745] {standard_task_runner.py:52} INFO - Started process 135 to run task
[2022-08-03 00:51:44,777] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'create_table', 'manual__2022-08-03T00:51:41.184193+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpduwhjvok', '--error-file', '/tmp/tmppv9u23d_']
[2022-08-03 00:51:44,797] {standard_task_runner.py:80} INFO - Job 21: Subtask create_table
[2022-08-03 00:51:45,524] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:51:41.184193+00:00 [running]> on host 4b5f29f024fc
[2022-08-03 00:51:45,981] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T00:51:41.184193+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T00:51:41.184193+00:00
[2022-08-03 00:51:46,031] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 00:51:46,056] {dbapi.py:231} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS users(
                    first_name TEXT NOT NULL,
                    last_name TEXT NOT NULL
                )
        , parameters: None
[2022-08-03 00:51:46,068] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-08-03 00:51:46,143] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ltv-pipeline, task_id=create_table, execution_date=20220803T005141, start_date=20220803T005144, end_date=20220803T005146
[2022-08-03 00:51:46,234] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-03 00:51:46,348] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
