[2022-08-03 16:34:39,679] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:34:20.083839+00:00 [queued]>
[2022-08-03 16:34:39,765] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:34:20.083839+00:00 [queued]>
[2022-08-03 16:34:39,776] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:34:39,785] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 16:34:39,791] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:34:39,825] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load-data> on 2022-08-03 16:34:20.083839+00:00
[2022-08-03 16:34:39,845] {standard_task_runner.py:52} INFO - Started process 1544 to run task
[2022-08-03 16:34:39,858] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'load-data', 'manual__2022-08-03T16:34:20.083839+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmp5cdwyrjl', '--error-file', '/tmp/tmpu0al5f26']
[2022-08-03 16:34:39,864] {standard_task_runner.py:80} INFO - Job 75: Subtask load-data
[2022-08-03 16:34:40,001] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:34:20.083839+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 16:34:40,166] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=load-data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T16:34:20.083839+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T16:34:20.083839+00:00
[2022-08-03 16:34:40,181] {postgres.py:127} INFO - Running copy expert: COPY logs FROM STDIN WITH DELIMITER ',' CSV HEADER , filename: <_io.TextIOWrapper name='/opt/airflow/files/vehicle_challenge.csv' mode='r' encoding='UTF-8'>
[2022-08-03 16:34:40,188] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 54, in insert_data
    post_hook.copy_expert("COPY logs FROM STDIN WITH DELIMITER ',' CSV HEADER ",f)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 128, in copy_expert
    if not os.path.isfile(filename):
  File "/usr/local/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper
[2022-08-03 16:34:40,228] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=load-data, execution_date=20220803T163420, start_date=20220803T163439, end_date=20220803T163440
[2022-08-03 16:34:40,264] {standard_task_runner.py:97} ERROR - Failed to execute job 75 for task load-data (stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper; 1544)
[2022-08-03 16:34:40,324] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 16:34:40,375] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
