[2022-08-03 17:25:47,119] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.decompress-file manual__2022-08-03T17:25:33.021034+00:00 [queued]>
[2022-08-03 17:25:47,155] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.decompress-file manual__2022-08-03T17:25:33.021034+00:00 [queued]>
[2022-08-03 17:25:47,161] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 17:25:47,164] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 17:25:47,170] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 17:25:47,275] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): decompress-file> on 2022-08-03 17:25:33.021034+00:00
[2022-08-03 17:25:47,301] {standard_task_runner.py:52} INFO - Started process 3644 to run task
[2022-08-03 17:25:47,310] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'decompress-file', 'manual__2022-08-03T17:25:33.021034+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpgmo0wmc9', '--error-file', '/tmp/tmpyqvkh67o']
[2022-08-03 17:25:47,316] {standard_task_runner.py:80} INFO - Job 99: Subtask decompress-file
[2022-08-03 17:25:47,577] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.decompress-file manual__2022-08-03T17:25:33.021034+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 17:25:48,068] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=decompress-file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T17:25:33.021034+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T17:25:33.021034+00:00
[2022-08-03 17:25:48,077] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-03 17:25:48,082] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'gunzip -f /opt/***/files/vehicle_challenge.csv.gz']
[2022-08-03 17:25:48,138] {subprocess.py:85} INFO - Output:
[2022-08-03 17:25:48,226] {subprocess.py:92} INFO - gzip: /opt/***/files/vehicle_challenge.csv.gz: No such file or directory
[2022-08-03 17:25:48,252] {subprocess.py:96} INFO - Command exited with return code 1
[2022-08-03 17:25:48,326] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-03 17:25:48,347] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=decompress-file, execution_date=20220803T172533, start_date=20220803T172547, end_date=20220803T172548
[2022-08-03 17:25:48,410] {standard_task_runner.py:97} ERROR - Failed to execute job 99 for task decompress-file (Bash command failed. The command returned a non-zero exit code 1.; 3644)
[2022-08-03 17:25:48,460] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 17:25:48,549] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
