[2022-08-03 00:35:03,239] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:34:58+00:00 [queued]>
[2022-08-03 00:35:03,356] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:34:58+00:00 [queued]>
[2022-08-03 00:35:03,365] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:35:03,374] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 00:35:03,383] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:35:03,441] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-08-03 00:34:58+00:00
[2022-08-03 00:35:03,518] {standard_task_runner.py:52} INFO - Started process 1932 to run task
[2022-08-03 00:35:03,535] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'create_table', 'manual__2022-08-03T00:34:58+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpfua1_feh', '--error-file', '/tmp/tmp63toyi4d']
[2022-08-03 00:35:03,566] {standard_task_runner.py:80} INFO - Job 5: Subtask create_table
[2022-08-03 00:35:03,958] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:34:58+00:00 [running]> on host dc3eb4614e33
[2022-08-03 00:35:04,574] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T00:34:58+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T00:34:58+00:00
[2022-08-03 00:35:04,652] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 00:35:04,684] {dbapi.py:231} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS users(
                    first_name TEXT NOT NULL,
                    last_name TEXT NOT NULL
                )
        , parameters: None
[2022-08-03 00:35:04,699] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-08-03 00:35:04,770] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ltv-pipeline, task_id=create_table, execution_date=20220803T003458, start_date=20220803T003503, end_date=20220803T003504
[2022-08-03 00:35:04,976] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-03 00:35:05,247] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
