[2022-08-03 00:41:12,200] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:41:07.345920+00:00 [queued]>
[2022-08-03 00:41:12,233] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:41:07.345920+00:00 [queued]>
[2022-08-03 00:41:12,240] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:41:12,246] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 00:41:12,261] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 00:41:12,353] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-08-03 00:41:07.345920+00:00
[2022-08-03 00:41:12,392] {standard_task_runner.py:52} INFO - Started process 144 to run task
[2022-08-03 00:41:12,406] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'create_table', 'manual__2022-08-03T00:41:07.345920+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpok76s0hg', '--error-file', '/tmp/tmpv23evgx3']
[2022-08-03 00:41:12,446] {standard_task_runner.py:80} INFO - Job 11: Subtask create_table
[2022-08-03 00:41:13,167] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.create_table manual__2022-08-03T00:41:07.345920+00:00 [running]> on host dc3eb4614e33
[2022-08-03 00:41:13,590] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T00:41:07.345920+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T00:41:07.345920+00:00
[2022-08-03 00:41:13,978] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 00:41:14,034] {dbapi.py:231} INFO - Running statement: 
                CREATE TABLE IF NOT EXISTS users(
                    first_name TEXT NOT NULL,
                    last_name TEXT NOT NULL
                )
        , parameters: None
[2022-08-03 00:41:14,055] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-08-03 00:41:14,144] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=ltv-pipeline, task_id=create_table, execution_date=20220803T004107, start_date=20220803T004112, end_date=20220803T004114
[2022-08-03 00:41:14,299] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-03 00:41:14,640] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
